version: '3.8'
services:

  event-manager:
    container_name: event-manager
    build:
      context: ./event_manager
      dockerfile: Dockerfile
    environment:
      SERVICE_PORT: ${LOCATION_SERVICE_PORT}
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://location_db:5432/${POSTGRES_DATABASE_LOCATION}'
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME_LOCATION}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_LOCATION}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    depends_on:
      location_db:
        condition: service_healthy
      kafka-1:
          condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - appnet

  location_db:
    image: postgres:16-alpine
    container_name: location_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_LOCATION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_LOCATION}
      POSTGRES_DB: ${POSTGRES_DATABASE_LOCATION}
    ports:
      - ${POSTGRES_PORT_MAPPING_LOCATION}
    volumes:
      - db-location-service:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME_LOCATION} -d ${POSTGRES_DATABASE_LOCATION} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - appnet

  event-notificator:
    container_name: event-notificator
    build:
      context: ./event_notificator
      dockerfile: Dockerfile
    environment:
      SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://notification_db:5432/${POSTGRES_DATABASE_NOTIFICATION}'
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME_NOTIFICATION}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_NOTIFICATION}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    depends_on:
      notification_db:
        condition: service_healthy
      kafka-1:
          condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - appnet

  notification_db:
    image: postgres:16-alpine
    container_name: notification_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_NOTIFICATION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_NOTIFICATION}
      POSTGRES_DB: ${POSTGRES_DATABASE_NOTIFICATION}
    ports:
      - ${POSTGRES_PORT_MAPPING_NOTIFICATION}
    volumes:
      - db-notification-service:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME_NOTIFICATION} -d ${POSTGRES_DATABASE_NOTIFICATION} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - appnet

  telegram-bot-service:
    container_name: telegram-bot-service
    build:
      context: ./telegram_bot_service
      dockerfile: Dockerfile
    environment:
      SERVICE_PORT: ${TELEGRAM_BOT_SERVICE_PORT}
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://telegram_bot_db:5432/${POSTGRES_DATABASE_TELEGRAM_BOT}'
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME_TELEGRAM_BOT}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_TELEGRAM_BOT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    depends_on:
      telegram_bot_db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - appnet

  telegram_bot_db:
    image: postgres:16-alpine
    container_name: telegram_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_TELEGRAM_BOT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TELEGRAM_BOT}
      POSTGRES_DB: ${POSTGRES_DATABASE_TELEGRAM_BOT}
    ports:
      - ${POSTGRES_PORT_MAPPING_TELEGRAM_BOT}
    volumes:
      - db-telegram-bot-service:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME_TELEGRAM_BOT} -d ${POSTGRES_DATABASE_TELEGRAM_BOT} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - appnet

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID='lm1k5MYRSOyXJhqnkeY3hA'
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_LISTENERS_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-1-data:/bitnami/kafka
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - appnet

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka_server
      dockerfile: Dockerfile
    image: eventhub-eureka-server:latest
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      SPRING_APPLICATION_NAME: eureka-server
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/eureka/apps" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ${GENERAL_SERVICE_PORT}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - appnet

volumes:
  db-location-service:
  db-notification-service:
  db-telegram-bot-service:
  kafka-1-data:
  redis_data:

networks:
  appnet:
    driver: bridge
