#Database
POSTGRES_SQL_USERNAME: location_service_admin
POSTGRES_SQL_PASSWORD: location_service_password
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5434
POSTGRES_SQL_DB: location_service_db

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#JWT
JWT_TOKEN_KEY: "56AA7E229742D19319E7C97241AA5594FA2C3710C0EF7E80B2B122C33B8AFC13"



